### ISSUE TITLE
Feature Request: Support `_VStackItemConvertible` etc. on `UILayoutGuide`

### ISSUE THREAD

**Issue by JohnEstropia** [muukii/MondrianLayout#48]
Since VStacks and HStacks currently only supports alignments and not "distributions" or "justification", 
I think `UILayoutGuide`s can help fill that gap (especially after https://github.com/muukii/MondrianLayout/issues/47 is implemented)

**Comment by muukii** [comment]
Sorry for missing justify options currently.
If you could, could you explain a bit more detailed design of that?
`StackingSpacer` does not help you?

**Comment by JohnEstropia** [comment]
Because currently `StackingSpacer` only allows setting the `minLength`, it's hard to express margins that have related sizes with other margins. For example, consider this example layout where the  separators and bottom margin is a percentage of the top margin:
```swift
--------------
| topMargin.height >= 10
--------------
| content1
--------------
| separator1.height == topMargin.height * 0.5
--------------
| content2
--------------
| bottomMargin.height ==  topMargin.height * 2
--------------
```

**Comment by muukii** [comment]
I think I understood.
which means, you're thinking laying  the layout guide in stack and specify the constraints of length by classical api?
