### ISSUE TITLE
Allow `[LayoutDescriptor]` in `@MondrianArrayBuilder` blocks

### ISSUE THREAD

**Issue by JohnEstropia** [muukii/MondrianLayout#50]
Sample use case:
```swift
mondrianBatchLayout {
    // ... other manual constraints

    buttons.map {
        $0.mondrian.layout.minHeight(44)
    }
}
```

**Comment by muukii** [comment]
it seems it's supposed to work already. syntax supported.
what's happening?

<img width="481" alt="CleanShot 2021-09-10 at 11 44 15@2x" src="https://user-images.githubusercontent.com/1888355/132791039-cb804e2a-2512-4feb-834e-6fdeb15fb1a2.png">

**Comment by JohnEstropia** [comment]
I don't think it works if there are other descriptors in the same closure:
```swift
mondrianBatchLayout {
    views[0].mondrian.layout.minHeight(44)

    views.dropFirst().map {
        $0.mondrian.layout.minHeight(44)
    }
}
```

**Comment by muukii** [comment]
@JohnEstropia now fixed by https://github.com/muukii/MondrianLayout/pull/51
