### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by bagusandinata** [muukii/MondrianLayout#75]
Hi @muukii, thanks for great library. Can I ask you, why min req ios version 12 ?

**Comment by muukii** [comment]
@bagusandinata 
Which version support do you need?

**Comment by muukii** [comment]
Oh- I see,
iOS 11 still have `topLayoutGuide`, `bottomLayoutGuide`. that's deprecated from iOS12, then we can lay out with `UILayoutGuide` including safe-area.

**Comment by bagusandinata** [comment]
Oh ok thanks @muukii , does it really have a big impact on libraries to have min ios 12 while in some libraries AutoLayout still supports ios 11? maybe a good idea to make it support ios 11 🥂 😄
